/* Generated By:JavaCC: Do not edit this line. CeCompiladorTreeConstants.java Version 7.0.12 */
package org.example.cecompilador.compilador;

public interface CeCompiladorTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTINSTRUCAO = 1;
  public int JJTBLOCOINSTRUCOES = 2;
  public int JJTDECLARACAOVARIAVEL = 3;
  public int JJTDECLARATIPO = 4;
  public int JJTATRIBUICAO = 5;
  public int JJTESTRUTURACONDICIONAL = 6;
  public int JJTESTRUTURAREPETICAO = 7;
  public int JJTESTRUTURAWHILE = 8;
  public int JJTESTRUTURADOWHILE = 9;
  public int JJTEXPRESSAO = 10;
  public int JJTEXPRESSAORELACIONAL = 11;
  public int JJTEXPRESSAOARITMETICA = 12;
  public int JJTTERMO = 13;
  public int JJTFATOR = 14;


  public String[] jjtNodeName = {
    "main",
    "instrucao",
    "blocoInstrucoes",
    "declaracaoVariavel",
    "declaraTipo",
    "atribuicao",
    "estruturaCondicional",
    "estruturaRepeticao",
    "estruturaWhile",
    "estruturaDoWhile",
    "expressao",
    "expressaoRelacional",
    "expressaoAritmetica",
    "termo",
    "fator",
  };
}
/* JavaCC - OriginalChecksum=60fd95daf46c32952a0c54f2f8222d19 (do not edit this line) */
