/* Generated By:JJTree&JavaCC: Do not edit this line. CeCompiladorConstants.java */
package org.example.cecompilador.compilador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CeCompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIAPROG = 5;
  /** RegularExpression Id. */
  int ABREBLOCO = 6;
  /** RegularExpression Id. */
  int FECHABLOCO = 7;
  /** RegularExpression Id. */
  int FIMINSTRUCAO = 8;
  /** RegularExpression Id. */
  int TIPOINT = 9;
  /** RegularExpression Id. */
  int TIPOFLOAT = 10;
  /** RegularExpression Id. */
  int TIPOBOL = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ABREPAR = 13;
  /** RegularExpression Id. */
  int FECHAPAR = 14;
  /** RegularExpression Id. */
  int OPREL = 15;
  /** RegularExpression Id. */
  int OPBOOL = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int COMMA = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int DOWHILE = 21;
  /** RegularExpression Id. */
  int OPAD = 22;
  /** RegularExpression Id. */
  int OPMULT = 23;
  /** RegularExpression Id. */
  int CONST_INT = 24;
  /** RegularExpression Id. */
  int CONST_FLOAT = 25;
  /** RegularExpression Id. */
  int DIGITO = 26;
  /** RegularExpression Id. */
  int ID = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"mein\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"inti\"",
    "\"flouti\"",
    "\"buleam\"",
    "\"ifi\"",
    "\"(\"",
    "\")\"",
    "<OPREL>",
    "<OPBOOL>",
    "\"=\"",
    "\",\"",
    "\"uaio\"",
    "\"du\"",
    "\"uaiu\"",
    "<OPAD>",
    "<OPMULT>",
    "<CONST_INT>",
    "<CONST_FLOAT>",
    "<DIGITO>",
    "<ID>",
  };

}
